#spring.application.name=CRUD-Springboot
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/product_api
#spring.datasource.username=postgres
#spring.datasource.password=Muqhtadeer@1234
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.springframework.security=DEBUG
#
#jwt.secret=MyVeryLongSecretKeyForJwtAuthentication2026DevelopmentOnly123456789
#jwt.expiration=900000
#jwt.refresh-expiration=604800000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false